### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
scalar_tensor = torch.tensor([7])
print(f"Scalar tensor: {scalar_tensor}")
print(f"Shape of scalar tensor: {scalar_tensor.shape}")

Scalar tensor: tensor([7])
Shape of scalar tensor: torch.Size([1])


### Convert a tensor to scalar

In [4]:
scalar_tensor = torch.tensor([7])
python_scalar = scalar_tensor.item()
print(f"Tensor: {scalar_tensor}")
print(f"Python Scalar: {python_scalar}")
print(f"Type of Python Scalar: {type(python_scalar)}")

Tensor: tensor([7])
Python Scalar: 7
Type of Python Scalar: <class 'int'>


### Creating 2D tensor

In [5]:
two_d_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6]])
print(f"2D Tensor:\n{two_d_tensor}")
print(f"Shape of 2D Tensor: {two_d_tensor.shape}")

2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of 2D Tensor: torch.Size([2, 3])


## Tensor and Numpy

### Convert from tensor to numpy array

In [6]:
tensor_data = torch.tensor([[1, 2, 3], [4, 5, 6]])
numpy_array = tensor_data.numpy()
print(f"Original Tensor:\n{tensor_data}")
print(f"Converted NumPy Array:\n{numpy_array}")
print(f"Type of NumPy Array: {type(numpy_array)}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Converted NumPy Array:
[[1 2 3]
 [4 5 6]]
Type of NumPy Array: <class 'numpy.ndarray'>


### Convert from numpy array to tensor

In [7]:
numpy_data = np.array([[10, 11, 12], [13, 14, 15]])
tensor_data_from_numpy = torch.from_numpy(numpy_data)
print(f"Original NumPy Array:\n{numpy_data}")
print(f"Converted Tensor:\n{tensor_data_from_numpy}")
print(f"Type of Converted Tensor: {type(tensor_data_from_numpy)}")

Original NumPy Array:
[[10 11 12]
 [13 14 15]]
Converted Tensor:
tensor([[10, 11, 12],
        [13, 14, 15]])
Type of Converted Tensor: <class 'torch.Tensor'>


## PyTorch and GPU

check if GPU is available

In [8]:
torch.cuda.is_available()

True

In [9]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

tensor_on_cpu = torch.tensor([1, 2, 3])
print(f"Tensor on CPU: {tensor_on_cpu}")

tensor_on_device = tensor_on_cpu.to(device)
print(f"Tensor on {device}: {tensor_on_device}")

Using device: cuda
Tensor on CPU: tensor([1, 2, 3])
Tensor on cuda: tensor([1, 2, 3], device='cuda:0')


## Basic operations

In [11]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor A:\n{tensor_a}")
print(f"Tensor B:\n{tensor_b}")
print(f"A + B:\n{tensor_a + tensor_b}")

print(f"A * B:\n{tensor_a * tensor_b}")

Tensor A:
tensor([[1, 2],
        [3, 4]])
Tensor B:
tensor([[5, 6],
        [7, 8]])
A + B:
tensor([[ 6,  8],
        [10, 12]])
A * B:
tensor([[ 5, 12],
        [21, 32]])


### Matrix multiplication

In [12]:
tensor_c = torch.tensor([[1, 2], [3, 4]])
tensor_d = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor C:\n{tensor_c}")
print(f"Tensor D:\n{tensor_d}")

# Matrix multiplication using torch.matmul()
matrix_mult_result_matmul = torch.matmul(tensor_c, tensor_d)
print(f"C @ D (using matmul):\n{matrix_mult_result_matmul}")

# Matrix multiplication using the @ operator (Python 3.5+)
matrix_mult_result_at = tensor_c @ tensor_d
print(f"C @ D (using @ operator):\n{matrix_mult_result_at}")

Tensor C:
tensor([[1, 2],
        [3, 4]])
Tensor D:
tensor([[5, 6],
        [7, 8]])
C @ D (using matmul):
tensor([[19, 22],
        [43, 50]])
C @ D (using @ operator):
tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [14]:
tensor_e = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print(f"Original Tensor E:\n{tensor_e}")

transposed_e_T = tensor_e.T
print(f"Transposed Tensor E (using .T):\n{transposed_e_T}")

transposed_e_transpose = torch.transpose(tensor_e, 0, 1)
print(f"Transposed Tensor E (using torch.transpose):\n{transposed_e_transpose}")

Original Tensor E:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed Tensor E (using .T):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Transposed Tensor E (using torch.transpose):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Creating a specific type of tensor

In [16]:
zeros_tensor = torch.zeros(2, 3)
print(f"Zeros Tensor (2x3):\n{zeros_tensor}")

ones_tensor = torch.ones(4, 2)
print(f"Ones Tensor (4x2):\n{ones_tensor}")

random_uniform_tensor = torch.rand(3, 3)
print(f"Random Uniform Tensor (3x3):\n{random_uniform_tensor}")

random_normal_tensor = torch.randn(2, 2)
print(f"Random Normal Tensor (2x2):\n{random_normal_tensor}")
empty_tensor = torch.empty(2, 2)
print(f"Empty Tensor (2x2):\n{empty_tensor}")

Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor (4x2):
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
Random Uniform Tensor (3x3):
tensor([[0.3926, 0.6280, 0.0518],
        [0.5455, 0.4389, 0.6870],
        [0.5702, 0.6461, 0.0220]])
Random Normal Tensor (2x2):
tensor([[-1.5322, -0.0880],
        [-1.9513,  1.4530]])
Empty Tensor (2x2):
tensor([[2.1410e+01, 0.0000e+00],
        [4.0821e-13, 4.4878e-41]])


## Tensor's shape

### Checking the shape of a tensor

In [ ]:
tensor_f = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Original Tensor F:\n{tensor_f}")
print(f"Shape of Tensor F: {tensor_f.shape}")

print(f"Number of dimensions: {tensor_f.ndim}")
print(f"Size of dimension 0: {tensor_f.shape[0]}")
print(f"Size of dimension 1: {tensor_f.shape[1]}")
print(f"Size of dimension 2: {tensor_f.shape[2]}")

### Changing the shape of a tensor

In [17]:
tensor_g = torch.arange(12)
print(f"Original Tensor G: {tensor_g}, Shape: {tensor_g.shape}")

reshaped_2x6 = tensor_g.reshape(2, 6)
print(f"Reshaped to 2x6:\n{reshaped_2x6}, Shape: {reshaped_2x6.shape}")

reshaped_3x4 = tensor_g.reshape(3, 4)
print(f"Reshaped to 3x4:\n{reshaped_3x4}, Shape: {reshaped_3x4.shape}")

reshaped_4x3 = tensor_g.reshape(4, -1)
print(f"Reshaped to 4x3 (inferred):\n{reshaped_4x3}, Shape: {reshaped_4x3.shape}")

reshaped_2x2x3 = tensor_g.reshape(2, 2, 3)
print(f"Reshaped to 2x2x3:\n{reshaped_2x2x3}, Shape: {reshaped_2x2x3.shape}")

Original Tensor G: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), Shape: torch.Size([12])
Reshaped to 2x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), Shape: torch.Size([2, 6])
Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), Shape: torch.Size([3, 4])
Reshaped to 4x3 (inferred):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), Shape: torch.Size([4, 3])
Reshaped to 2x2x3:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]), Shape: torch.Size([2, 2, 3])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [18]:
tensor_h = torch.tensor([[1, 2], [3, 4]])
tensor_i = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor H:\n{tensor_h}")
print(f"Tensor I:\n{tensor_i}")

stacked_dim0 = torch.stack([tensor_h, tensor_i], dim=0)
print(f"\nStacked (dim=0):\n{stacked_dim0}")
print(f"Shape of stacked (dim=0): {stacked_dim0.shape}")

stacked_dim1 = torch.stack([tensor_h, tensor_i], dim=1)
print(f"\nStacked (dim=1):\n{stacked_dim1}")
print(f"Shape of stacked (dim=1): {stacked_dim1.shape}")

Tensor H:
tensor([[1, 2],
        [3, 4]])
Tensor I:
tensor([[5, 6],
        [7, 8]])

Stacked (dim=0):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape of stacked (dim=0): torch.Size([2, 2, 2])

Stacked (dim=1):
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
Shape of stacked (dim=1): torch.Size([2, 2, 2])


In [19]:
tensor_j = torch.tensor([[1, 2], [3, 4]])
tensor_k = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor J:\n{tensor_j}")
print(f"Tensor K:\n{tensor_k}")

concatenated_dim0 = torch.cat([tensor_j, tensor_k], dim=0)
print(f"\nConcatenated (dim=0):\n{concatenated_dim0}")
print(f"Shape of concatenated (dim=0): {concatenated_dim0.shape}")

concatenated_dim1 = torch.cat([tensor_j, tensor_k], dim=1)
print(f"\nConcatenated (dim=1):\n{concatenated_dim1}")
print(f"Shape of concatenated (dim=1): {concatenated_dim1.shape}")

Tensor J:
tensor([[1, 2],
        [3, 4]])
Tensor K:
tensor([[5, 6],
        [7, 8]])

Concatenated (dim=0):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Shape of concatenated (dim=0): torch.Size([4, 2])

Concatenated (dim=1):
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Shape of concatenated (dim=1): torch.Size([2, 4])


### Squeezing a tensor (removing an extra dimension)

In [20]:
tensor_l = torch.zeros(1, 4, 1, 3)
print(f"Original Tensor L:\n{tensor_l}")
print(f"Shape of Original Tensor L: {tensor_l.shape}")

squeezed_tensor = torch.squeeze(tensor_l)
print(f"\nSqueezed Tensor:\n{squeezed_tensor}")
print(f"Shape of Squeezed Tensor: {squeezed_tensor.shape}")

tensor_m = torch.zeros(2, 1, 5)
print(f"\nOriginal Tensor M:\n{tensor_m}")
print(f"Shape of Original Tensor M: {tensor_m.shape}")

squeezed_dim1 = torch.squeeze(tensor_m, dim=1)
print(f"\nSqueezed Tensor (dim=1):\n{squeezed_dim1}")
print(f"Shape of Squeezed Tensor (dim=1): {squeezed_dim1.shape}")

Original Tensor L:
tensor([[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]]])
Shape of Original Tensor L: torch.Size([1, 4, 1, 3])

Squeezed Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Shape of Squeezed Tensor: torch.Size([4, 3])

Original Tensor M:
tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])
Shape of Original Tensor M: torch.Size([2, 1, 5])

Squeezed Tensor (dim=1):
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape of Squeezed Tensor (dim=1): torch.Size([2, 5])


### Unsqueezing a tensor (adding an extra dimension)

In [21]:
tensor_n = torch.arange(6)
print(f"Original Tensor N: {tensor_n}, Shape: {tensor_n.shape}")

unsqueezed_dim0 = torch.unsqueeze(tensor_n, dim=0)
print(f"\nUnsqueezed (dim=0):\n{unsqueezed_dim0}, Shape: {unsqueezed_dim0.shape}")

unsqueezed_dim1 = torch.unsqueeze(tensor_n, dim=1)
print(f"\nUnsqueezed (dim=1):\n{unsqueezed_dim1}, Shape: {unsqueezed_dim1.shape}")

unsqueezed_method = tensor_n.unsqueeze(dim=0)
print(f"\nUnsqueezed (using method):\n{unsqueezed_method}, Shape: {unsqueezed_method.shape}")

Original Tensor N: tensor([0, 1, 2, 3, 4, 5]), Shape: torch.Size([6])

Unsqueezed (dim=0):
tensor([[0, 1, 2, 3, 4, 5]]), Shape: torch.Size([1, 6])

Unsqueezed (dim=1):
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]), Shape: torch.Size([6, 1])

Unsqueezed (using method):
tensor([[0, 1, 2, 3, 4, 5]]), Shape: torch.Size([1, 6])


## Indexing

In [22]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [23]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [24]:
X = torch.randn(200, 7)
print(f"Shape of X: {X.shape}")

b = torch.randn(8, 1)
print(f"Shape of b: {b.shape}")

e = torch.randn(200, 1)
print(f"Shape of e: {e.shape}")

Shape of X: torch.Size([200, 7])
Shape of b: torch.Size([8, 1])
Shape of e: torch.Size([200, 1])


In [25]:
ones_tensor = torch.ones(200, 1)
print(f"Shape of ones_tensor: {ones_tensor.shape}")
print(f"First 5 rows of ones_tensor:\n{ones_tensor[:5]}")

Shape of ones_tensor: torch.Size([200, 1])
First 5 rows of ones_tensor:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [26]:
X = torch.cat((ones_tensor, X), dim=1)
print(f"New shape of X: {X.shape}")
print(f"First 5 rows of X:\n{X[:5]}")

New shape of X: torch.Size([200, 8])
First 5 rows of X:
tensor([[ 1.0000,  0.0051, -0.6006, -0.7079,  0.6585,  0.4791, -1.6411, -1.3068],
        [ 1.0000, -1.7341,  0.7854, -0.9239,  0.2153,  0.1063,  0.6701, -0.9349],
        [ 1.0000, -0.6395,  0.0821, -0.3973, -1.0581,  1.3987,  0.3698,  0.8524],
        [ 1.0000,  0.4663, -0.7160,  0.2884,  0.1790, -2.1318, -0.1148, -0.0935],
        [ 1.0000,  1.2219, -0.8965, -0.7240, -0.1837, -1.3102, -0.3265,  0.4833]])


In [27]:
y = X @ b + e
print(f"Shape of y: {y.shape}")
print(f"First 5 rows of y:\n{y[:5]}")

Shape of y: torch.Size([200, 1])
First 5 rows of y:
tensor([[ 1.2074],
        [-0.6838],
        [-2.0963],
        [ 1.2140],
        [ 2.6152]])


In [28]:
X_transpose = X.T
print(f"Shape of X_transpose: {X_transpose.shape}")

X_transpose_X = X_transpose @ X
print(f"Shape of X_transpose_X: {X_transpose_X.shape}")

X_transpose_X_inverse = torch.inverse(X_transpose_X)
print(f"Shape of (X_transpose X)^-1: {X_transpose_X_inverse.shape}")

X_transpose_y = X_transpose @ y
print(f"Shape of X_transpose y: {X_transpose_y.shape}")

b_hat = X_transpose_X_inverse @ X_transpose_y
print(f"Shape of b_hat: {b_hat.shape}")
print(f"First 5 rows of b_hat:\n{b_hat[:5]}")

Shape of X_transpose: torch.Size([8, 200])
Shape of X_transpose_X: torch.Size([8, 8])
Shape of (X_transpose X)^-1: torch.Size([8, 8])
Shape of X_transpose y: torch.Size([8, 1])
Shape of b_hat: torch.Size([8, 1])
First 5 rows of b_hat:
tensor([[ 0.0228],
        [ 0.8699],
        [ 0.7420],
        [-1.0373],
        [-0.4348]])


In [29]:
y_hat = X @ b_hat
print(f"Shape of y_hat: {y_hat.shape}")
print(f"First 5 rows of y_hat:\n{y_hat[:5]}")

Shape of y_hat: torch.Size([200, 1])
First 5 rows of y_hat:
tensor([[ 0.7584],
        [-0.8652],
        [-2.0687],
        [ 2.9165],
        [ 3.5999]])


In [30]:
y_numpy = y.numpy()
y_hat_numpy = y_hat.numpy()

differences = y_numpy - y_hat_numpy
squared_differences = differences**2
sum_squared_differences = np.sum(squared_differences)

mse = sum_squared_differences / 200

print(f"y_numpy shape: {y_numpy.shape}")
print(f"y_hat_numpy shape: {y_hat_numpy.shape}")
print(f"Calculated MSE: {mse}")

y_numpy shape: (200, 1)
y_hat_numpy shape: (200, 1)
Calculated MSE: 0.9514442682266235
